// @generated — do not edit by hand.
// Regenerated by `maelstrom-build` from the JSON schema via `build.rs`.

#[allow(dead_code)]
#[derive(::serde::Deserialize, ::serde::Serialize)]
pub struct Init {
    pub node_id: ::std::string::String,
    pub node_ids: ::std::vec::Vec<::std::string::String>,
}
#[derive(::serde::Serialize)]
pub struct InitOk {}
#[allow(dead_code)]
#[derive(::serde::Deserialize, ::serde::Serialize)]
pub struct Echo {
    pub echo: ::std::string::String,
}
#[derive(::serde::Serialize)]
pub struct EchoOk {
    pub echo: ::std::string::String,
}
pub trait EchoApi {
    fn init(
        &self,
        req: maelstrom::message::Request<Init>,
    ) -> impl ::std::future::Future<
        Output = ::std::result::Result<
            maelstrom::message::Response<InitOk>,
            maelstrom::error::ErrorCode,
        >,
    > + ::std::marker::Send;
    fn echo(
        &self,
        req: maelstrom::message::Request<Echo>,
    ) -> impl ::std::future::Future<
        Output = ::std::result::Result<
            maelstrom::message::Response<EchoOk>,
            maelstrom::error::ErrorCode,
        >,
    > + ::std::marker::Send;
}
pub struct EchoServer<T>(::std::sync::Arc<T>);
impl<T> EchoServer<T> {
    pub fn new(inner: T) -> Self {
        Self(::std::sync::Arc::new(inner))
    }
}
impl<T> maelstrom::service::Service<maelstrom::message::Request<::serde_json::Value>>
    for EchoServer<T>
where
    T: EchoApi + ::std::marker::Send + ::std::marker::Sync,
{
    type Response = maelstrom::message::Response<::serde_json::Value>;
    type Error = maelstrom::error::Error;
    async fn call(
        &mut self,
        req: maelstrom::message::Request<::serde_json::Value>,
    ) -> ::std::result::Result<Self::Response, Self::Error> {
        match req.metadata().kind.as_str() {
            "init" => {
                let inner = ::std::sync::Arc::clone(&self.0);
                unary(move |r| async move { inner.init(r).await }, req).await
            }
            "echo" => {
                let inner = ::std::sync::Arc::clone(&self.0);
                unary(move |r| async move { inner.echo(r).await }, req).await
            }
            _kind => Err(maelstrom::error::Error::from(
                maelstrom::error::ErrorCode::NotSupported,
            )),
        }
    }
}
async fn unary<F, Fut, ReqBody, ResBody>(
    f: F,
    req: maelstrom::message::Request<::serde_json::Value>,
) -> ::std::result::Result<maelstrom::message::Response<::serde_json::Value>, maelstrom::error::Error>
where
    F: ::std::ops::FnOnce(maelstrom::message::Request<ReqBody>) -> Fut + ::std::marker::Send,
    Fut: ::std::future::Future<
            Output = ::std::result::Result<
                maelstrom::message::Response<ResBody>,
                maelstrom::error::ErrorCode,
            >,
        > + ::std::marker::Send,
    ReqBody: ::serde::de::DeserializeOwned + ::std::marker::Send,
    ResBody: ::serde::Serialize + ::std::marker::Send,
{
    let (metadata, body_value) = req.into_parts();
    let typed_body: ReqBody = ::serde_json::from_value(body_value).map_err(|_| {
        maelstrom::error::Error::from(maelstrom::error::ErrorCode::MalformedRequest)
    })?;
    let typed_req = maelstrom::message::Request::new(metadata, typed_body);
    let response = f(typed_req).await.map_err(maelstrom::error::Error::from)?;
    let (res_metadata, res_body) = response.into_parts();
    Ok(maelstrom::message::Response::new(
        res_metadata,
        ::serde_json::to_value(res_body).expect("failed to serialize response body"),
    ))
}
