//! Build-time code generator for Maelstrom services.
//!
//! Analogous to `tonic-build` / `prost-build`: call [`compile`] from your
//! `build.rs` and then `include!` the generated file in your source tree.
//!
//! # Example
//!
//! ```rust,no_run
//! // build.rs
//! fn main() {
//!     maelstrom_build::compile("schema/echo.json").unwrap();
//! }
//! ```
//!
//! ```rust,ignore
//! // src/rpc.rs
//! include!(concat!(env!("OUT_DIR"), "/echo.rs"));
//! ```

use proc_macro2::Span;
use quote::quote;
use serde::Deserialize;
use std::path::Path;

// The outer envelope describes the RPC structure (message names, request /
// response pairing).  The `request` / `response` bodies are standard JSON
// Schema `object` definitions, consumable by any language tooling.

#[derive(Deserialize)]
struct Schema {
    service: String,
    messages: Vec<MessageDef>,
}

#[derive(Deserialize)]
struct MessageDef {
    /// Maelstrom `type` string for the request, e.g. `"echo"`.
    name: String,
    /// Maelstrom `type` string for the response, e.g. `"echo_ok"`.
    response_type: String,
    /// JSON Schema object describing the request body fields.
    request: ObjectSchema,
    /// JSON Schema object describing the response body fields.
    response: ObjectSchema,
}

/// A JSON Schema `{ "type": "object", "properties": {…}, "required": […] }`.
/// Unknown JSON Schema keywords (e.g. `"$schema"`, `"title"`) are ignored.
#[derive(Deserialize, Default)]
struct ObjectSchema {
    #[serde(default)]
    properties: serde_json::Map<String, serde_json::Value>,
    #[serde(default)]
    required: Vec<String>,
}

/// Supported subset of JSON Schema scalar / composite types.
#[derive(Deserialize)]
#[serde(tag = "type")]
enum JsonSchema {
    #[serde(rename = "string")]
    Str,
    #[serde(rename = "integer")]
    Integer,
    #[serde(rename = "number")]
    Number,
    #[serde(rename = "boolean")]
    Boolean,
    #[serde(rename = "null")]
    Null,
    #[serde(rename = "array")]
    Array { items: Box<JsonSchema> },
}

/// Read a JSON Schema protocol descriptor and write generated Rust source to
/// `src/rpc.rs` inside the calling crate (relative to `CARGO_MANIFEST_DIR`).
///
/// `schema_path` is resolved relative to `CARGO_MANIFEST_DIR` when it is a
/// relative path (i.e. relative to the crate that owns the `build.rs`).
///
/// Emits `cargo:rerun-if-changed` so Cargo recompiles only when the schema
/// file actually changes.
pub fn compile(schema_path: impl AsRef<Path>) -> Result<(), Box<dyn std::error::Error>> {
    let schema_path = {
        let p = schema_path.as_ref();
        if p.is_relative() {
            let manifest = std::env::var("CARGO_MANIFEST_DIR")?;
            std::path::PathBuf::from(manifest).join(p)
        } else {
            p.to_path_buf()
        }
    };

    // Tell Cargo to re-run build.rs only when the schema file changes.
    println!("cargo:rerun-if-changed={}", schema_path.display());

    let content = std::fs::read_to_string(&schema_path)?;
    let schema: Schema = serde_json::from_str(&content)?;

    let tokens = generate(schema);

    // Parse tokens into a syn::File and format with prettyplease so the
    // generated code is human-readable when committed to the source tree.
    let syntax_tree = syn::parse2(tokens)?;
    let formatted = prettyplease::unparse(&syntax_tree);

    let header = "// @generated — do not edit by hand.\n// Regenerated by `maelstrom-build` from the JSON schema via `build.rs`.\n\n";

    let manifest = std::env::var("CARGO_MANIFEST_DIR")?;
    let out_path = Path::new(&manifest).join("src").join("rpc.rs");
    std::fs::write(&out_path, format!("{header}{formatted}"))?;

    Ok(())
}

fn generate(schema: Schema) -> proc_macro2::TokenStream {
    let service = &schema.service;
    let api_ident = ident(&format!("{}Api", service));
    let server_ident = ident(&format!("{}Server", service));

    let mut struct_tokens: Vec<proc_macro2::TokenStream> = vec![];
    let mut trait_methods: Vec<proc_macro2::TokenStream> = vec![];
    let mut match_arms: Vec<proc_macro2::TokenStream> = vec![];

    for msg in &schema.messages {
        // "echo"    → Echo     (request struct)
        // "echo_ok" → EchoOk   (response struct)
        let req_ident = ident(&pascal_case(&msg.name));
        let res_ident = ident(&pascal_case(&msg.response_type));
        let method_ident = ident(&msg.name);
        let msg_type_str = &msg.name;

        let req_fields = object_fields(&msg.request);
        struct_tokens.push(quote! {
            #[allow(dead_code)]
            #[derive(::serde::Deserialize, ::serde::Serialize)]
            pub struct #req_ident {
                #(#req_fields),*
            }
        });

        let res_fields = object_fields(&msg.response);
        struct_tokens.push(quote! {
            #[derive(::serde::Serialize)]
            pub struct #res_ident {
                #(#res_fields),*
            }
        });

        trait_methods.push(quote! {
            fn #method_ident(
                req: maelstrom::message::Request<#req_ident>,
            ) -> impl ::std::future::Future<
                Output = ::std::result::Result<
                    maelstrom::message::Response<#res_ident>,
                    maelstrom::error::ErrorCode,
                >,
            > + ::std::marker::Send;
        });

        match_arms.push(quote! {
            #msg_type_str => unary(|r| T::#method_ident(r), req).await,
        });
    }

    let unary_fn = unary_tokens();

    quote! {
        #(#struct_tokens)*

        pub trait #api_ident {
            #(#trait_methods)*
        }

        pub struct #server_ident<T>(::std::marker::PhantomData<T>);

        impl<T> ::std::default::Default for #server_ident<T> {
            fn default() -> Self {
                Self(::std::marker::PhantomData)
            }
        }

        impl<T> maelstrom::service::Service<
            maelstrom::message::Request<::serde_json::Value>
        > for #server_ident<T>
        where
            T: #api_ident + ::std::marker::Send,
        {
            type Response = maelstrom::message::Response<::serde_json::Value>;
            type Error = maelstrom::error::Error;

            async fn call(
                &mut self,
                req: maelstrom::message::Request<::serde_json::Value>,
            ) -> ::std::result::Result<Self::Response, Self::Error> {
                match req.metadata().kind.as_str() {
                    #(#match_arms)*
                    _kind => Err(maelstrom::error::Error::from(
                        maelstrom::error::ErrorCode::NotSupported,
                    )),
                }
            }
        }

        #unary_fn
    }
}

fn unary_tokens() -> proc_macro2::TokenStream {
    quote! {
        async fn unary<F, Fut, ReqBody, ResBody>(
            f: F,
            req: maelstrom::message::Request<::serde_json::Value>,
        ) -> ::std::result::Result<
            maelstrom::message::Response<::serde_json::Value>,
            maelstrom::error::Error,
        >
        where
            F: ::std::ops::FnOnce(maelstrom::message::Request<ReqBody>) -> Fut + ::std::marker::Send,
            Fut: ::std::future::Future<
                Output = ::std::result::Result<
                    maelstrom::message::Response<ResBody>,
                    maelstrom::error::ErrorCode,
                >,
            > + ::std::marker::Send,
            ReqBody: ::serde::de::DeserializeOwned + ::std::marker::Send,
            ResBody: ::serde::Serialize + ::std::marker::Send,
        {
            let (metadata, body_value) = req.into_parts();
            let typed_body: ReqBody = ::serde_json::from_value(body_value)
                .map_err(|_| maelstrom::error::Error::from(maelstrom::error::ErrorCode::MalformedRequest))?;
            let typed_req = maelstrom::message::Request::new(metadata, typed_body);
            let response = f(typed_req).await.map_err(maelstrom::error::Error::from)?;
            let (res_metadata, res_body) = response.into_parts();
            Ok(maelstrom::message::Response::new(
                res_metadata,
                ::serde_json::to_value(res_body).expect("failed to serialize response body"),
            ))
        }
    }
}

fn object_fields(schema: &ObjectSchema) -> Vec<proc_macro2::TokenStream> {
    schema
        .properties
        .iter()
        .map(|(field_name, field_value)| {
            let name = ident(field_name);
            let field_schema: JsonSchema = serde_json::from_value(field_value.clone())
                .unwrap_or_else(|e| {
                    panic!("Invalid JSON Schema for property {:?}: {}", field_name, e)
                });
            let optional = !schema.required.contains(field_name);
            let ty = json_schema_to_type(&field_schema, optional);
            quote! { pub #name: #ty }
        })
        .collect()
}

fn json_schema_to_type(schema: &JsonSchema, optional: bool) -> proc_macro2::TokenStream {
    let base = match schema {
        JsonSchema::Str => quote! { ::std::string::String },
        JsonSchema::Integer => quote! { i64 },
        JsonSchema::Number => quote! { f64 },
        JsonSchema::Boolean => quote! { bool },
        JsonSchema::Null => quote! { () },
        JsonSchema::Array { items } => {
            let inner = json_schema_to_type(items, false);
            quote! { ::std::vec::Vec<#inner> }
        }
    };

    if optional {
        quote! { ::std::option::Option<#base> }
    } else {
        base
    }
}

fn pascal_case(s: &str) -> String {
    s.split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}

fn ident(s: &str) -> syn::Ident {
    syn::Ident::new(s, Span::call_site())
}
