//! Build-time code generator for Maelstrom services.
//!
//! Analogous to `tonic-build` / `prost-build`: call [`compile`] from your
//! `build.rs` and then `include!` the generated file in your source tree.
//!
//! # Example
//!
//! ```rust,no_run
//! // build.rs
//! fn main() {
//!     maelstrom_build::compile("schema/echo.json").unwrap();
//! }
//! ```
//!
//! ```rust,ignore
//! // src/rpc.rs
//! include!(concat!(env!("OUT_DIR"), "/echo.rs"));
//! ```

use proc_macro2::Span;
use quote::quote;
use schemars::schema::{RootSchema, SchemaObject};
use serde::Deserialize;
use std::path::Path;
use typify::{TypeSpace, TypeSpaceSettings};

#[derive(Deserialize)]
struct Schema {
    service: String,
    messages: Vec<MessageDef>,
}

#[derive(Deserialize)]
struct MessageDef {
    /// Maelstrom `type` string for the request, e.g. `"echo"`.
    name: String,
    /// Maelstrom `type` string for the response, e.g. `"echo_ok"`.
    response_type: String,
    /// Raw JSON Schema object describing the request body fields.
    request: serde_json::Value,
    /// Raw JSON Schema object describing the response body fields.
    response: serde_json::Value,
}

/// Read a JSON Schema protocol descriptor and write generated Rust source to
/// `src/rpc.rs` inside the calling crate (relative to `CARGO_MANIFEST_DIR`).
pub fn compile(schema_path: impl AsRef<Path>) -> Result<(), Box<dyn std::error::Error>> {
    let schema_path = {
        let p = schema_path.as_ref();
        if p.is_relative() {
            let manifest = std::env::var("CARGO_MANIFEST_DIR")?;
            std::path::PathBuf::from(manifest).join(p)
        } else {
            p.to_path_buf()
        }
    };

    println!("cargo:rerun-if-changed={}", schema_path.display());

    let content = std::fs::read_to_string(&schema_path)?;
    let schema: Schema = serde_json::from_str(&content)?;

    let type_tokens = generate_types(&schema)?;
    let rpc_tokens = generate_rpc(&schema);

    let all_tokens = quote! {
        #type_tokens
        #rpc_tokens
    };

    let syntax_tree = syn::parse2(all_tokens)?;
    let formatted = prettyplease::unparse(&syntax_tree);

    let header = "// @generated — do not edit by hand.\n// Regenerated by `maelstrom-build` from the JSON schema via `build.rs`.\n\n#![allow(dead_code)]\n\n";

    let manifest = std::env::var("CARGO_MANIFEST_DIR")?;
    let out_path = Path::new(&manifest).join("src").join("rpc.rs");
    std::fs::write(&out_path, format!("{header}{formatted}"))?;

    Ok(())
}

/// Generate struct definitions for all message request/response bodies via typify.
fn generate_types(schema: &Schema) -> Result<proc_macro2::TokenStream, Box<dyn std::error::Error>> {
    let mut definitions = schemars::Map::new();

    for msg in &schema.messages {
        let req_name = pascal_case(&msg.name);
        let res_name = pascal_case(&msg.response_type);

        let req_schema: schemars::schema::Schema = serde_json::from_value(close_empty_object(msg.request.clone()))?;
        let res_schema: schemars::schema::Schema = serde_json::from_value(close_empty_object(msg.response.clone()))?;

        definitions.insert(req_name, req_schema);
        definitions.insert(res_name, res_schema);
    }

    let root = RootSchema {
        meta_schema: None,
        schema: SchemaObject::default(),
        definitions,
    };

    let mut type_space = TypeSpace::new(&TypeSpaceSettings::default());
    type_space.add_root_schema(root)?;

    Ok(type_space.to_stream())
}

/// Typify generates a newtype over `serde_json::Map` for any `{"type": "object"}` schema
/// that has no `additionalProperties` constraint, even when `properties` is empty.
/// Adding `"additionalProperties": false` tells typify the object is closed and it
/// generates a proper empty struct instead.
fn close_empty_object(mut value: serde_json::Value) -> serde_json::Value {
    if let Some(obj) = value.as_object_mut() {
        let props_empty = obj
            .get("properties")
            .and_then(|p| p.as_object())
            .map_or(true, |p| p.is_empty());
        let no_additional = !obj.contains_key("additionalProperties");
        if props_empty && no_additional {
            obj.insert(
                "additionalProperties".to_string(),
                serde_json::Value::Bool(false),
            );
        }
    }
    value
}

/// Generate the service trait, server dispatcher, and typed client.
fn generate_rpc(schema: &Schema) -> proc_macro2::TokenStream {
    let service = &schema.service;
    let api_ident = ident(&format!("{}Api", service));
    let server_ident = ident(&format!("{}Server", service));
    let client_ident = ident(&format!("{}Client", service));

    let mut trait_methods: Vec<proc_macro2::TokenStream> = vec![];
    let mut match_arms: Vec<proc_macro2::TokenStream> = vec![];
    let mut client_methods: Vec<proc_macro2::TokenStream> = vec![];

    for msg in &schema.messages {
        let req_ident = ident(&pascal_case(&msg.name));
        let res_ident = ident(&pascal_case(&msg.response_type));
        let method_ident = ident(&msg.name);
        let msg_type_str = &msg.name;
        let res_type_str = &msg.response_type;

        trait_methods.push(quote! {
            fn #method_ident(
                &self,
                req: maelstrom::message::Request<#req_ident>,
            ) -> impl ::std::future::Future<
                Output = ::std::result::Result<
                    maelstrom::message::Response<#res_ident>,
                    maelstrom::error::ErrorCode,
                >,
            > + ::std::marker::Send;
        });

        match_arms.push(quote! {
            #msg_type_str => {
                let inner = ::std::sync::Arc::clone(&self.0);
                unary(#res_type_str, move |r| async move { inner.#method_ident(r).await }, req).await
            }
        });

        client_methods.push(quote! {
            pub async fn #method_ident(
                &self,
                dest: impl ::std::convert::Into<::std::string::String>,
                req: #req_ident,
            ) -> ::std::result::Result<#res_ident, maelstrom::error::Error> {
                let reply = self.inner.rpc(dest, #msg_type_str, &req).await?;
                ::serde_json::from_value(reply.body.payload).map_err(|_| {
                    maelstrom::error::Error::from(maelstrom::error::ErrorCode::MalformedRequest)
                })
            }
        });
    }

    let unary_fn = unary_tokens();

    quote! {
        pub trait #api_ident {
            #(#trait_methods)*
        }

        pub struct #server_ident<T>(::std::sync::Arc<T>);

        impl<T> #server_ident<T> {
            pub fn new(inner: T) -> Self {
                Self(::std::sync::Arc::new(inner))
            }
        }

        impl<T> maelstrom::service::Service<
            maelstrom::message::Request<::serde_json::Value>
        > for #server_ident<T>
        where
            T: #api_ident + ::std::marker::Send + ::std::marker::Sync,
        {
            type Response = maelstrom::message::Message<::serde_json::Value>;
            type Error = maelstrom::error::Error;

            async fn call(
                &mut self,
                req: maelstrom::message::Request<::serde_json::Value>,
            ) -> ::std::result::Result<Self::Response, Self::Error> {
                match req.metadata().kind.as_str() {
                    #(#match_arms)*
                    _kind => Err(maelstrom::error::Error::from(
                        maelstrom::error::ErrorCode::NotSupported,
                    )),
                }
            }
        }

        #[derive(Clone)]
        pub struct #client_ident {
            inner: maelstrom::Client,
        }

        impl #client_ident {
            pub fn new() -> Self {
                Self { inner: maelstrom::Client::new() }
            }

            #(#client_methods)*
        }

        impl ::std::default::Default for #client_ident {
            fn default() -> Self {
                Self::new()
            }
        }

        #unary_fn
    }
}

fn unary_tokens() -> proc_macro2::TokenStream {
    quote! {
        async fn unary<F, Fut, ReqBody, ResBody>(
            response_type: &'static str,
            f: F,
            req: maelstrom::message::Request<::serde_json::Value>,
        ) -> ::std::result::Result<
            maelstrom::message::Message<::serde_json::Value>,
            maelstrom::error::Error,
        >
        where
            F: ::std::ops::FnOnce(maelstrom::message::Request<ReqBody>) -> Fut + ::std::marker::Send,
            Fut: ::std::future::Future<
                Output = ::std::result::Result<
                    maelstrom::message::Response<ResBody>,
                    maelstrom::error::ErrorCode,
                >,
            > + ::std::marker::Send,
            ReqBody: ::serde::de::DeserializeOwned + ::std::marker::Send,
            ResBody: ::serde::Serialize + ::std::marker::Send,
        {
            let (req_meta, body_value) = req.into_parts();
            let typed_body: ReqBody = ::serde_json::from_value(body_value)
                .map_err(|_| maelstrom::error::Error::from(maelstrom::error::ErrorCode::MalformedRequest))?;
            let typed_req = maelstrom::message::Request::new(req_meta.clone(), typed_body);
            let response = f(typed_req).await.map_err(maelstrom::error::Error::from)?;
            let (override_meta, res_body) = response.into_parts();
            let meta = override_meta.unwrap_or_else(|| maelstrom::message::Metadata {
                src: req_meta.dest,
                dest: req_meta.src,
                kind: response_type.to_string(),
                msg_id: None,
                in_reply_to: req_meta.msg_id,
            });
            Ok(maelstrom::message::Message {
                src: meta.src,
                dest: meta.dest,
                body: maelstrom::message::Body {
                    kind: meta.kind,
                    msg_id: meta.msg_id,
                    in_reply_to: meta.in_reply_to,
                    payload: ::serde_json::to_value(res_body).expect("failed to serialize response body"),
                },
            })
        }
    }
}

fn pascal_case(s: &str) -> String {
    s.split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}

fn ident(s: &str) -> syn::Ident {
    syn::Ident::new(s, Span::call_site())
}
