// @generated — do not edit by hand.
// Regenerated by `maelstrom-build` from the JSON schema via `build.rs`.

#![allow(dead_code)]

/// Error types.
pub mod error {
    /// Error from a TryFrom or FromStr implementation.
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(
            &self,
            f: &mut ::std::fmt::Formatter<'_>,
        ) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(
            &self,
            f: &mut ::std::fmt::Formatter<'_>,
        ) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}
///Broadcast
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "required": [
///    "message"
///  ],
///  "properties": {
///    "message": {
///      "type": "integer"
///    }
///  }
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct Broadcast {
    pub message: i64,
}
impl From<&Broadcast> for Broadcast {
    fn from(value: &Broadcast) -> Self {
        value.clone()
    }
}
///BroadcastOk
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct BroadcastOk {}
impl From<&BroadcastOk> for BroadcastOk {
    fn from(value: &BroadcastOk) -> Self {
        value.clone()
    }
}
///Init
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "required": [
///    "node_id",
///    "node_ids"
///  ],
///  "properties": {
///    "node_id": {
///      "type": "string"
///    },
///    "node_ids": {
///      "type": "array",
///      "items": {
///        "type": "string"
///      }
///    }
///  }
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct Init {
    pub node_id: String,
    pub node_ids: Vec<String>,
}
impl From<&Init> for Init {
    fn from(value: &Init) -> Self {
        value.clone()
    }
}
///InitOk
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct InitOk {}
impl From<&InitOk> for InitOk {
    fn from(value: &InitOk) -> Self {
        value.clone()
    }
}
///Read
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct Read {}
impl From<&Read> for Read {
    fn from(value: &Read) -> Self {
        value.clone()
    }
}
///ReadOk
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "required": [
///    "messages"
///  ],
///  "properties": {
///    "messages": {
///      "type": "array",
///      "items": {
///        "type": "integer"
///      }
///    }
///  }
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct ReadOk {
    pub messages: Vec<i64>,
}
impl From<&ReadOk> for ReadOk {
    fn from(value: &ReadOk) -> Self {
        value.clone()
    }
}
///Topology
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "required": [
///    "topology"
///  ],
///  "properties": {
///    "topology": {
///      "type": "object",
///      "additionalProperties": {
///        "type": "array",
///        "items": {
///          "type": "string"
///        }
///      }
///    }
///  }
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct Topology {
    pub topology: ::std::collections::HashMap<String, Vec<String>>,
}
impl From<&Topology> for Topology {
    fn from(value: &Topology) -> Self {
        value.clone()
    }
}
///TopologyOk
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct TopologyOk {}
impl From<&TopologyOk> for TopologyOk {
    fn from(value: &TopologyOk) -> Self {
        value.clone()
    }
}
pub trait BroadcastApi {
    fn init(
        &self,
        req: maelstrom::message::Request<Init>,
    ) -> impl ::std::future::Future<
        Output = ::std::result::Result<
            maelstrom::message::Response<InitOk>,
            maelstrom::error::ErrorCode,
        >,
    > + ::std::marker::Send;
    fn topology(
        &self,
        req: maelstrom::message::Request<Topology>,
    ) -> impl ::std::future::Future<
        Output = ::std::result::Result<
            maelstrom::message::Response<TopologyOk>,
            maelstrom::error::ErrorCode,
        >,
    > + ::std::marker::Send;
    fn broadcast(
        &self,
        req: maelstrom::message::Request<Broadcast>,
    ) -> impl ::std::future::Future<
        Output = ::std::result::Result<
            maelstrom::message::Response<BroadcastOk>,
            maelstrom::error::ErrorCode,
        >,
    > + ::std::marker::Send;
    fn read(
        &self,
        req: maelstrom::message::Request<Read>,
    ) -> impl ::std::future::Future<
        Output = ::std::result::Result<
            maelstrom::message::Response<ReadOk>,
            maelstrom::error::ErrorCode,
        >,
    > + ::std::marker::Send;
}
pub struct BroadcastServer<T>(::std::sync::Arc<T>);
impl<T> BroadcastServer<T> {
    pub fn new(inner: T) -> Self {
        Self(::std::sync::Arc::new(inner))
    }
}
impl<T> maelstrom::service::Service<maelstrom::message::Request<::serde_json::Value>>
for BroadcastServer<T>
where
    T: BroadcastApi + ::std::marker::Send + ::std::marker::Sync,
{
    type Response = maelstrom::message::Message<::serde_json::Value>;
    type Error = maelstrom::error::Error;
    async fn call(
        &mut self,
        req: maelstrom::message::Request<::serde_json::Value>,
    ) -> ::std::result::Result<Self::Response, Self::Error> {
        match req.metadata().kind.as_str() {
            "init" => {
                let inner = ::std::sync::Arc::clone(&self.0);
                unary("init_ok", move |r| async move { inner.init(r).await }, req).await
            }
            "topology" => {
                let inner = ::std::sync::Arc::clone(&self.0);
                unary(
                        "topology_ok",
                        move |r| async move { inner.topology(r).await },
                        req,
                    )
                    .await
            }
            "broadcast" => {
                let inner = ::std::sync::Arc::clone(&self.0);
                unary(
                        "broadcast_ok",
                        move |r| async move { inner.broadcast(r).await },
                        req,
                    )
                    .await
            }
            "read" => {
                let inner = ::std::sync::Arc::clone(&self.0);
                unary("read_ok", move |r| async move { inner.read(r).await }, req).await
            }
            _kind => {
                Err(
                    maelstrom::error::Error::from(
                        maelstrom::error::ErrorCode::NotSupported,
                    ),
                )
            }
        }
    }
}
#[derive(Clone)]
pub struct BroadcastClient {
    inner: maelstrom::Client,
}
impl BroadcastClient {
    pub fn new() -> Self {
        Self {
            inner: maelstrom::Client::new(),
        }
    }
    pub async fn init(
        &self,
        dest: impl ::std::convert::Into<::std::string::String>,
        req: Init,
    ) -> ::std::result::Result<InitOk, maelstrom::error::Error> {
        let reply = self.inner.rpc(dest, "init", &req).await?;
        ::serde_json::from_value(reply.body.payload)
            .map_err(|_| {
                maelstrom::error::Error::from(
                    maelstrom::error::ErrorCode::MalformedRequest,
                )
            })
    }
    pub async fn topology(
        &self,
        dest: impl ::std::convert::Into<::std::string::String>,
        req: Topology,
    ) -> ::std::result::Result<TopologyOk, maelstrom::error::Error> {
        let reply = self.inner.rpc(dest, "topology", &req).await?;
        ::serde_json::from_value(reply.body.payload)
            .map_err(|_| {
                maelstrom::error::Error::from(
                    maelstrom::error::ErrorCode::MalformedRequest,
                )
            })
    }
    pub async fn broadcast(
        &self,
        dest: impl ::std::convert::Into<::std::string::String>,
        req: Broadcast,
    ) -> ::std::result::Result<BroadcastOk, maelstrom::error::Error> {
        let reply = self.inner.rpc(dest, "broadcast", &req).await?;
        ::serde_json::from_value(reply.body.payload)
            .map_err(|_| {
                maelstrom::error::Error::from(
                    maelstrom::error::ErrorCode::MalformedRequest,
                )
            })
    }
    pub async fn read(
        &self,
        dest: impl ::std::convert::Into<::std::string::String>,
        req: Read,
    ) -> ::std::result::Result<ReadOk, maelstrom::error::Error> {
        let reply = self.inner.rpc(dest, "read", &req).await?;
        ::serde_json::from_value(reply.body.payload)
            .map_err(|_| {
                maelstrom::error::Error::from(
                    maelstrom::error::ErrorCode::MalformedRequest,
                )
            })
    }
}
impl ::std::default::Default for BroadcastClient {
    fn default() -> Self {
        Self::new()
    }
}
async fn unary<F, Fut, ReqBody, ResBody>(
    response_type: &'static str,
    f: F,
    req: maelstrom::message::Request<::serde_json::Value>,
) -> ::std::result::Result<
    maelstrom::message::Message<::serde_json::Value>,
    maelstrom::error::Error,
>
where
    F: ::std::ops::FnOnce(maelstrom::message::Request<ReqBody>) -> Fut
        + ::std::marker::Send,
    Fut: ::std::future::Future<
            Output = ::std::result::Result<
                maelstrom::message::Response<ResBody>,
                maelstrom::error::ErrorCode,
            >,
        > + ::std::marker::Send,
    ReqBody: ::serde::de::DeserializeOwned + ::std::marker::Send,
    ResBody: ::serde::Serialize + ::std::marker::Send,
{
    let (req_meta, body_value) = req.into_parts();
    let typed_body: ReqBody = ::serde_json::from_value(body_value)
        .map_err(|_| maelstrom::error::Error::from(
            maelstrom::error::ErrorCode::MalformedRequest,
        ))?;
    let typed_req = maelstrom::message::Request::new(req_meta.clone(), typed_body);
    let response = f(typed_req).await.map_err(maelstrom::error::Error::from)?;
    let (override_meta, res_body) = response.into_parts();
    let meta = override_meta
        .unwrap_or_else(|| maelstrom::message::Metadata {
            src: req_meta.dest,
            dest: req_meta.src,
            kind: response_type.to_string(),
            msg_id: None,
            in_reply_to: req_meta.msg_id,
        });
    Ok(maelstrom::message::Message {
        src: meta.src,
        dest: meta.dest,
        body: maelstrom::message::Body {
            kind: meta.kind,
            msg_id: meta.msg_id,
            in_reply_to: meta.in_reply_to,
            payload: ::serde_json::to_value(res_body)
                .expect("failed to serialize response body"),
        },
    })
}
